### PR TITLE
Kitura stack fix

### LINKED ISSUE #533: Kitura: appsody test failure
Appsody stack validate fails with this during the test stage:

[Container] Running command:  swift test
[Container] [ControllerDebug] New process created with pid 16
[Container] [ControllerDebug] Started RUN/DEBUG/TEST process
/project/user-app/Tests/ApplicationTests/KituraStackTests.swift:121:19: error: use of undeclared type 'URLRequest'
[Container] private extension URLRequest {
[Container]                   ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:44:9: error: use of unresolved identifier 'URLRequest'
[Container]         URLRequest(forTestWithMethod: "GET", port: AppsodyKitura.port, route: AppsodyKitura.livenessPath)?
[Container]         ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:65:9: error: use of unresolved identifier 'URLRequest'
[Container]         URLRequest(forTestWithMethod: "GET", port: AppsodyKitura.port, route: AppsodyKitura.openAPIPath)?
[Container]         ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:101:9: error: use of unresolved identifier 'URLRequest'
[Container]         URLRequest(forTestWithMethod: "GET", port: AppsodyKitura.port, route: AppsodyKitura.metricsPath)?
[Container]         ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:131:13: error: use of unresolved identifier 'addValue'
[Container]             addValue("application/json", forHTTPHeaderField: "Content-Type")
[Container]             ^~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:132:13: error: use of unresolved identifier 'httpMethod'
[Container]             httpMethod = method
[Container]             ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:133:13: error: use of unresolved identifier 'cachePolicy'
[Container]             cachePolicy = .reloadIgnoringCacheData
[Container]             ^~~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:135:17: error: use of unresolved identifier 'httpBody'
[Container]                 httpBody = body
[Container]                 ^~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:148:25: error: use of unresolved identifier 'url'
[Container]         guard let url = url else {
[Container]                         ^~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:151:28: error: use of unresolved identifier 'httpMethod'
[Container]         guard let method = httpMethod, let headers = allHTTPHeaderFields, let host = url.host, let port = url.port else {
[Container]                            ^~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:151:54: error: use of unresolved identifier 'allHTTPHeaderFields'
[Container]         guard let method = httpMethod, let headers = allHTTPHeaderFields, let host = url.host, let port = url.port else {
[Container]                                                      ^~~~~~~~~~~~~~~~~~~
[Container] /project/user-app/Tests/ApplicationTests/KituraStackTests.swift:188:27: error: use of unresolved identifier 'httpBody'
[Container]         if let dataBody = httpBody {
[Container]                           ^~~~~~~~
[260/264] W[Debug] CLI exit error is:  exit status 1

### PR DESCRIPTION
**Pull request by CameronMcWilliam**
### Checklist:

- [x] Read the [Code of Conduct](https://github.com/appsody/website/blob/master/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md).

- [x] Followed the [commit message guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).

- [x] Stack adheres to [Appsody stack structure](https://github.com/appsody/website/blob/master/content/docs/stacks/stack-structure.md).

### Modifying an existing stack:

- [x] Updated the stack version in `stack.yaml`

Added `import FoundationNetworking` at the top of test file.

### Related Issues:
fixes #533

### CODE REVIEW

File: incubator/kitura/templates/default/Tests/ApplicationTests/KituraStackTests.swift [hunk 1]
```diff
@@ -3,6 +3,11 @@ import Kitura
 import KituraNet
 import XCTest
 import AppsodyKitura
+#if swift(>=4.1)
```
Comment (djones6) [inline incubator/kitura/templates/default/Tests/ApplicationTests/KituraStackTests.swift]: This is fine, but this stack is never going to be used with Swift 4.0, so we could simplify this by removing the version check.
